---
- name: Debug Webhook Events
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
 
  rules:
    - name: Debug incoming webhook event
      condition: true
      action:
        debug:
          msg: |
            Received Event:
            {{ event | to_nice_json }}
 
